/**
 * Provides PIG UDF Loader for RDF Data.
 * <p>
 * Only an extended N-Triples format is supported at the moment.
 * Beyond the syntax of N-Triples this format supports some commonly used prefixes
 * as well as typed literals. The loader can be used to load the RDF data
 * generated by the SP2Bench SPARQL Performance Benchmark generator.
 * <p>
 * Turtle or N3 format is not supported because it is incompatible with the
 * way data is loaded in the Hadoop framework (HDFS).
 * <p>
 * This package is compatible with the PIG API up to version 0.6.0.
 *
 * @see <a href="http://dbis.informatik.uni-freiburg.de/index.php?project=SP2B">SP2Bench SPARQL Performance Benchmark</a>
 * 
 * @author Alexander Schaetzle
 * @version 1.0
 */
package pigsparql.rdfLoader;

